[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Ville Penttinen <villem.penttinen@gmail.com>"]
edition = "2018"

[[bin]]
name = "day01"
path = "src/day01.rs"


[[bin]]
name = "day02"
path = "src/day02.rs"

[[bin]]
name = "day03"
path = "src/day03.rs"

[dependencies]
regex = "1"